name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@v11
        with:
          environment-file: false
          environment-name: TEST
          channels: conda-forge

      - name: Python ${{ matrix.python-version }}
        shell: bash -l {0}
        run: |
          micromamba create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt
          micromamba activate TEST
          pip install -e . --no-deps --force-reinstall
          micromamba info --all
          micromamba list

      - name: Tests
        shell: bash -l {0}
        run: |
          micromamba activate TEST
          pytest -rxs --cov=xpublish_edr tests
